### ISSUE TITLE
Edit page is broken

### ISSUE THREAD

**Issue by ralphonthefloor** [ralphonthefloor/Recipe-Book#20]
ReferenceError: recipe is not defined
    at D:\Web Development\RecipeBook\Recipe-Book\app.js:176:26
    at Layer.handle [as handle_request] (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\layer.js:95:5)
    at D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\index.js:341:12)
    at next (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\index.js:275:10)
    at serveStatic (D:\Web Development\RecipeBook\Recipe-Book\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (D:\Web Development\RecipeBook\Recipe-Book\node_modules\express\lib\router\layer.js:95:5)

**Comment by ralphonthefloor** [comment]
//edit recipe route
app.post('/edit', function(req, res) {
  console.log("posted to /edit");
  console.log(req.body.selectedrecipe);
  const id = req.body.selectedrecipe;
  **Recipe.findById(id, function(err, recipe) {**
    if (err) {
      console.log(err);
      res.send(err);
    } else {
      console.log(recipe);
      res.render("edit", {
        recipe: recipe
      });
    }
  });
});


Update mongoose function. Pretty sure it was a type from the last merge. Must have updated the wrong function/route
